Importing Libraries


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Import Dataset

In [2]:
#Import Dataset
ds= pd.read_csv("dataset_website.csv")
ds.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [3]:
#Analysing the data using pandas and Checking if the dataset contains any Null values.
ds.info()
ds.isnull().any() #no nullvalues

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

Taking care of missing data

In [4]:
ds.isnull().any()   #no missing data in the dataset

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

No need of applying label/one hot encoding as there are no categorical columns in the dataset.

Feature scaling is not required as data is already present in the same range.

Splitting data as independent and dependent

In [5]:
#Splitting data as independent and dependent
#removing index column in independent dataset
x=ds.iloc[:,1:31].values
y=ds.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


In [6]:
y=ds.iloc[:,-1].values
y

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

Splitting data into train and test 

In [7]:
#Splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

MODEL BUILDING -

Since the output (result) is  categorical , it comes under classification model.

Training and Testing the model -

1. LOGISTIC REGRESSION -

In [8]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [9]:
lr.fit(x_train,y_train)

LogisticRegression()

In [10]:
y_pred1=lr.predict(x_test)

In [11]:
y_pred1=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)
log_reg

0.9167797376752601

2. KNN-euclidian distance

In [12]:
from sklearn.neighbors import KNeighborsClassifier
kn1=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)  


In [13]:
kn1.fit(x_train,y_train)

KNeighborsClassifier()

In [14]:
y_pred2=kn1.predict(x_test)
from sklearn.metrics import accuracy_score
knn_euc=accuracy_score(y_test,y_pred2)
knn_euc


0.9434644957033017

3. KNN-manhattan distance

In [15]:
kn2=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=1)
kn2.fit(x_train,y_train) 

KNeighborsClassifier(p=1)

In [16]:
y_pred3=kn2.predict(x_test)
from sklearn.metrics import accuracy_score
knn_man=accuracy_score(y_test,y_pred3)
knn_man

0.9479873360470376

4. SVM -rbf

In [17]:
from sklearn.svm import SVC
svm1=SVC(kernel='rbf')
svm1.fit(x_train,y_train) 

SVC()

In [18]:
y_pred4=svm1.predict(x_test)
from sklearn.metrics import accuracy_score
svm_rbf=accuracy_score(y_test,y_pred4)
svm_rbf

0.9407507914970602

5. SVM -sigmoid

In [19]:
svm2=SVC(kernel='sigmoid')
svm2.fit(x_train,y_train) 

SVC(kernel='sigmoid')

In [20]:
y_pred5=svm2.predict(x_test)
from sklearn.metrics import accuracy_score
svm_sig=accuracy_score(y_test,y_pred5)
svm_sig

0.8326549072817729

6. DECISION TREE

In [21]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [22]:
y_pred6=dt.predict(x_test)
from sklearn.metrics import accuracy_score
dec_tree=accuracy_score(y_test,y_pred6)
dec_tree

0.9620081411126187

7. RANDOM FOREST

In [23]:
from sklearn.ensemble import RandomForestRegressor
Rf=RandomForestRegressor(n_estimators=10,random_state=0,n_jobs=-1)     
Rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=0)

In [24]:
y_pred7=Rf.predict(x_test)
from sklearn.metrics import accuracy_score
rf=accuracy_score(y_test,y_pred7.round())
rf

0.9285391225689733

8. NAIVE BAYES

In [25]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_train,y_train)

GaussianNB()

In [26]:
y_pred8=gb.predict(x_test)
from sklearn.metrics import accuracy_score
nb=accuracy_score(y_test,y_pred1)
nb

0.9167797376752601

Model Comparision

In [27]:
models = pd.DataFrame({
    'Model': [ 'Logistic Regression', 'KNN-eiclidian distance','KNN-manhattan distance','Naive Bayes','SVM-rbf','SVM-sigmoid','Decision Tree','Random Forest'],
    'Test Score': [ log_reg,knn_euc,knn_man,nb,svm_rbf,svm_sig,dec_tree,rf]})
models.sort_values(by='Test Score', ascending=False)

Model  Test Score
6           Decision Tree    0.962008
2  KNN-manhattan distance    0.947987
1  KNN-eiclidian distance    0.943464
4                 SVM-rbf    0.940751
7           Random Forest    0.928539
0     Logistic Regression    0.916780
3             Naive Bayes    0.916780
5             SVM-sigmoid    0.832655

To avoid overfitting , the model which is considered here is LOGISTIC REGRESSION

ACCURACY OF DECISION TREE MODEL IS HIGHEST 

In [28]:
import joblib
joblib.dump(models,'Phishing_Website.pkl')

['Phishing_Website.pkl']